name: AdvancedChunkHoppers
description: $description
version: '${version}'

main: net.omni.ach.AdvancedChunkHoppers
api-version: '1.13'
load: POSTWORLD

softdepend: [ GangsPlus, RoseStacker ]

authors: [ domninos ]
