name: AdvancedChunkHoppers
description: $description
version: '${version}'

main: net.omni.ach.AdvancedChunkHoppers
api-version: '1.13'
load: POSTWORLD

softdepend: [ GangsPlus, RoseStacker, CustomCrafting, LuckPerms ]

authors: [ domninos ]

commands:
  advancedchunkhopper:
    usage: /<command>
    description: Basic command for AdvancedChunkHoppers
    aliases: [ach]
